language: php
sudo: true
php:
- 5.4
- 5.5
- 5.6
- hhvm
- nightly
before_install:
    - sudo apt-get install -qq checkinstall
script: make test
before_deploy: sudo checkinstall --type=debian --pkgname=xp-runners --pkgversion=5.6.2 --pkggroup=devel --pkglicense=BSD --pkgarch all -y --requires=php5-cli,realpath --backup=no --install=no --nodoc --reset-uids=yes make unix.install
deploy:
  provider: bintray
  file: bintray.descriptor.json
  user: mikey179
  key:
    secure: PZeSv7zyCI1CzapMp4kPz39GjIomAgRhTBLQ5WjVklc8cyrhOki+x8Wq7GllJk/hv8j5Sr99n1SQDszcca3lh7xkdr9eeZOTSbyeQS0oy6Ncq3/5WJjlL7YqyyhAUfvluaIg9+8C4Qd8QaYV6XBL75j81ctC3uBhALFT1lTuXHt4uDxPn/6w7k10UkL1NtXsAom9T507pVvS1d72TCXWdPN4vQPp1FxxyjNFcQwlhzMbIqddFhG5iNu7TVbWXnZWbbeMPrp/M81lrynT6uMvo2yvhFfVOs0OPlZOdpbAHQgQdoBcV64O8z9kiUyDDZEYGkxaufICqVDps4SK97EF1pqKaGMiruY7/3qORAuhm+y2bqEe8Adt257pSNg/9DfI9t2/jfN6qiE+7OW9q/NWK1ITi1w9txNcRFOpCuaJMAwLeha9NKZQnr5L3ZjtVJOYd5Clq4fhoAedCg1Q3r7mLpzuCiPastfzt6bZI3b32/eyGcFpKwY64BfYx2/7147pyg4b45zGyAx1tclcBwD0U5oAkLA1cVmWt3CKFbTlghuv7U1wLZL/xbQCwflhReMs6Sd6qHnJAJhuae6sedzXxbFdpwDTXEVGjMcoBDRDdV3Bx/BZqbRbUoQ3sySLQrR1v5XPl3CSnoaAWZx3MpaZfBv5ZoSUdymSYuzCusqGn8M=
  dry-run: true
